export const ADD_BUCKET = "ADD_BUCKET";
export const ADD_LIST_ITEM = "ADD_LIST_ITEM";
export const ADD_CURRENT_ID = "ADD_CURRENT_ID";
export const UPDATE_LIST_ITEM = "UPDATE_LIST_ITEM";
export const UPDATE_LIST_ITEM_STATUS = "UPDATE_LIST_ITEM_STATUS";
export const DELETE_LIST_ITEM = "DELETE_LIST_ITEM";
